import type { Metadata } from "next";
import "./globals.css";

import { Head } from "next/document";

export const metadata: Metadata = {
  title: "Youcef Ha",
  description: "Generated by create next app",

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <head>
        <link rel="icon" href="./lightning.svg" />

        </head>
      <body
        className={` antialiased overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
